<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<ImplicitUsings>enable</ImplicitUsings>
		<PublishAot>True</PublishAot>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'RELEASE'">
		<PackageReference Include="LightORM.Extensions.DependencyInjection" Version="*" />
		<PackageReference Include="LightORM.Providers.Sqlite" Version="*" />
		<PackageReference Include="LightORM.Providers.SqlServer" Version="*" />
		<PackageReference Include="LightORM.Providers.MySql" Version="*" />
		<PackageReference Include="LightORM.Providers.Oracle" Version="*" />
		<PackageReference Include="LightORM.Providers.PostgreSQL" Version="*" />
		<PackageReference Include="LightORM.Providers.Dameng" Version="*" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' == 'DEBUG'">
		<ProjectReference Include="..\src\Providers\LightORM.Providers.SqlServer\LightORM.Providers.SqlServer.csproj" />
		<ProjectReference Include="..\src\Providers\LightORM.Providers.MySql\LightORM.Providers.MySql.csproj" />
		<ProjectReference Include="..\src\Providers\LightORM.Providers.Oracle\LightORM.Providers.Oracle.csproj" />
		<ProjectReference Include="..\src\Providers\LightORM.Providers.PostgreSQL\LightORM.Providers.PostgreSQL.csproj" />
		<ProjectReference Include="..\src\Providers\LightORM.Providers.Dameng\LightORM.Providers.Dameng.csproj" />
		<ProjectReference Include="..\src\LightOrmTableContextGenerator\LightOrmTableContextGenerator.csproj" OutputItemType="Analyzer" />
		<ProjectReference Include="..\src\LightORM.Extensions.DependencyInjection\LightORM.Extensions.DependencyInjection.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.0.4" />
		<PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
	</ItemGroup>
</Project>
