// <auto-generated/>
#nullable enable
#pragma warning disable CS0168
#pragma warning disable CS0219
#pragma warning disable CS1591

namespace LightORM.GeneratedTableContext;

/// <summary>
/// LightOrmTableContextGenerator 为 <see cref="global::LightORMTest.Models.Product"/> 生成的反序列化器。
/// 生成策略：Fast 档 —— 列绑定计划（Plan）+ 静态类型分派 switch 全展开。
/// </summary>
internal sealed class ProductDeserializer
    : global::LightORM.Utils.ReaderPlanCache<ProductDeserializer.Plan>
{
    // ---------------------------------------------------------------
    // 列绑定计划：一次 Bind，之后每行复用
    //   <Name>       : 列序号，-1 表示本次查询没查出这一列（保持属性默认值）
    //   <Name>_Kind  : reader.GetFieldType(i) 归一化后的类型
    // ---------------------------------------------------------------
    internal sealed class Plan
    {
        public int Id = -1;
        public global::LightORM.Utils.FieldKind Id_Kind;

        public int ProductId = -1;
        public global::LightORM.Utils.FieldKind ProductId_Kind;

        public int CategoryId = -1;
        public global::LightORM.Utils.FieldKind CategoryId_Kind;

        public int ProductCode = -1;
        public global::LightORM.Utils.FieldKind ProductCode_Kind;

        public int ProductName = -1;
        public global::LightORM.Utils.FieldKind ProductName_Kind;

        public int DeleteMark = -1;
        public global::LightORM.Utils.FieldKind DeleteMark_Kind;

        public int CreateTime = -1;
        public global::LightORM.Utils.FieldKind CreateTime_Kind;

        public int ModifyTime = -1;
        public global::LightORM.Utils.FieldKind ModifyTime_Kind;
    }

    /// <summary>对应 ITableEntityInfo&lt;T&gt;.DataReaderDeserializer</summary>
    public static readonly global::System.Func<global::System.Data.IDataReader, global::LightORMTest.Models.Product> Instance = Deserialize;

    private static readonly ProductDeserializer _cache = new();

    // ---------------------------------------------------------------
    // 入口
    // ---------------------------------------------------------------
    public static global::LightORMTest.Models.Product Deserialize(global::System.Data.IDataReader reader)
    {
        var plan = _cache.Get(reader);

        // 用对象初始化器而不是 "new + 逐条赋值"：
        //   1) 支持 init-only 属性（Product.CreateTime 是 init）
        //   2) 支持 readonly/init 的宿主属性做 Flat 嵌套
        // ReadXxx 都是 private static 小方法，JIT 会内联
        return new global::LightORMTest.Models.Product
        {
            Id = Read_Id(reader, plan),
            ProductId = Read_ProductId(reader, plan),
            CategoryId = Read_CategoryId(reader, plan),
            ProductCode = Read_ProductCode(reader, plan)!,
            ProductName = Read_ProductName(reader, plan)!,
            DeleteMark = Read_DeleteMark(reader, plan),
            CreateTime = Read_CreateTime(reader, plan),
            ModifyTime = Read_ModifyTime(reader, plan),
        };
    }

    // ---------------------------------------------------------------
    // 列绑定：每个 schema 只跑一次
    // 大小写变体：原样 / 全大写 / 全小写，覆盖 Oracle(全大写)、MySQL(原样)、PostgreSQL(全小写)
    // C# 编译器对 7+ case 的字符串 switch 会自动生成静态 Dictionary 查找，零分配
    // ---------------------------------------------------------------
    protected override Plan Bind(global::System.Data.IDataReader reader)
    {
        var plan = new Plan();
        int count = reader.FieldCount;
        for (int i = 0; i < count; i++)
        {
            var kind = global::LightORM.Utils.FieldKindResolver.Resolve(reader.GetFieldType(i));
            switch (reader.GetName(i))
            {
                case "Id":
                case "ID":
                case "id":
                    plan.Id = i; plan.Id_Kind = kind; break;

                case "PRODUCT_ID":
                case "product_id":
                    plan.ProductId = i; plan.ProductId_Kind = kind; break;

                case "CATEGORY_ID":
                case "category_id":
                    plan.CategoryId = i; plan.CategoryId_Kind = kind; break;

                case "PRODUCT_CODE":
                case "product_code":
                    plan.ProductCode = i; plan.ProductCode_Kind = kind; break;

                case "PRODUCT_NAME":
                case "product_name":
                    plan.ProductName = i; plan.ProductName_Kind = kind; break;

                case "DELETE_MARK":
                case "delete_mark":
                    plan.DeleteMark = i; plan.DeleteMark_Kind = kind; break;

                case "CREATE_TIME":
                case "create_time":
                    plan.CreateTime = i; plan.CreateTime_Kind = kind; break;

                case "MODIFY_TIME":
                case "modify_time":
                    plan.ModifyTime = i; plan.ModifyTime_Kind = kind; break;
            }
        }

        return plan;
    }

    // ---------------------------------------------------------------
    // 逐列读取（Fast 档：switch 展开在本类型内部，无委托、无装箱、无 GetSchemaTable）
    // 空值：统一无条件 IsDBNull 检查 —— 见 README 的"为什么不做 AllowDBNull 预判"
    // ---------------------------------------------------------------

    // System.Int32
    private static int Read_Id(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.Id;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.Id_Kind)
        {
            case global::LightORM.Utils.FieldKind.Int32: return r.GetInt32(o);
            case global::LightORM.Utils.FieldKind.Int64: return (int)r.GetInt64(o);
            case global::LightORM.Utils.FieldKind.Int16: return r.GetInt16(o);
            case global::LightORM.Utils.FieldKind.Byte: return r.GetByte(o);
            case global::LightORM.Utils.FieldKind.Decimal: return (int)r.GetDecimal(o);
            case global::LightORM.Utils.FieldKind.Double: return (int)r.GetDouble(o);
            case global::LightORM.Utils.FieldKind.Single: return (int)r.GetFloat(o);
            case global::LightORM.Utils.FieldKind.Boolean: return r.GetBoolean(o) ? 1 : 0;
            case global::LightORM.Utils.FieldKind.String: return int.Parse(r.GetString(o), global::System.Globalization.CultureInfo.CurrentCulture);
            default: return (int)global::System.Convert.ChangeType(r.GetValue(o), typeof(int), global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }

    // System.Int32  [LightColumn(PRODUCT_ID)]
    private static int Read_ProductId(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.ProductId;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.ProductId_Kind)
        {
            case global::LightORM.Utils.FieldKind.Int32: return r.GetInt32(o);
            case global::LightORM.Utils.FieldKind.Int64: return (int)r.GetInt64(o);
            case global::LightORM.Utils.FieldKind.Int16: return r.GetInt16(o);
            case global::LightORM.Utils.FieldKind.Byte: return r.GetByte(o);
            case global::LightORM.Utils.FieldKind.Decimal: return (int)r.GetDecimal(o);
            case global::LightORM.Utils.FieldKind.Double: return (int)r.GetDouble(o);
            case global::LightORM.Utils.FieldKind.Single: return (int)r.GetFloat(o);
            case global::LightORM.Utils.FieldKind.String: return int.Parse(r.GetString(o), global::System.Globalization.CultureInfo.CurrentCulture);
            default: return (int)global::System.Convert.ChangeType(r.GetValue(o), typeof(int), global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }

    // System.Int32  [LightColumn(CATEGORY_ID)]
    private static int Read_CategoryId(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.CategoryId;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.CategoryId_Kind)
        {
            case global::LightORM.Utils.FieldKind.Int32: return r.GetInt32(o);
            case global::LightORM.Utils.FieldKind.Int64: return (int)r.GetInt64(o);
            case global::LightORM.Utils.FieldKind.Int16: return r.GetInt16(o);
            case global::LightORM.Utils.FieldKind.Byte: return r.GetByte(o);
            case global::LightORM.Utils.FieldKind.Decimal: return (int)r.GetDecimal(o);
            case global::LightORM.Utils.FieldKind.Double: return (int)r.GetDouble(o);
            case global::LightORM.Utils.FieldKind.Single: return (int)r.GetFloat(o);
            case global::LightORM.Utils.FieldKind.String: return int.Parse(r.GetString(o), global::System.Globalization.CultureInfo.CurrentCulture);
            default: return (int)global::System.Convert.ChangeType(r.GetValue(o), typeof(int), global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }

    // System.String  [LightColumn(PRODUCT_CODE)]
    private static string? Read_ProductCode(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.ProductCode;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.ProductCode_Kind)
        {
            case global::LightORM.Utils.FieldKind.String: return r.GetString(o);
            case global::LightORM.Utils.FieldKind.Char: return r.GetChar(o).ToString();
            case global::LightORM.Utils.FieldKind.Guid: return r.GetGuid(o).ToString();
            case global::LightORM.Utils.FieldKind.Bytes: return global::System.Text.Encoding.UTF8.GetString(global::LightORM.Utils.DataReaderConvert.ToBytes(r, o));
            default:
                var v = r.GetValue(o);
                return v is null or global::System.DBNull ? null : global::System.Convert.ToString(v, global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }

    // System.String  [LightColumn(PRODUCT_NAME)]
    private static string? Read_ProductName(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.ProductName;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.ProductName_Kind)
        {
            case global::LightORM.Utils.FieldKind.String: return r.GetString(o);
            case global::LightORM.Utils.FieldKind.Char: return r.GetChar(o).ToString();
            case global::LightORM.Utils.FieldKind.Guid: return r.GetGuid(o).ToString();
            case global::LightORM.Utils.FieldKind.Bytes: return global::System.Text.Encoding.UTF8.GetString(global::LightORM.Utils.DataReaderConvert.ToBytes(r, o));
            default:
                var v = r.GetValue(o);
                return v is null or global::System.DBNull ? null : global::System.Convert.ToString(v, global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }

    // System.Boolean  [LightColumn(DELETE_MARK)]
    private static bool Read_DeleteMark(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.DeleteMark;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.DeleteMark_Kind)
        {
            case global::LightORM.Utils.FieldKind.Boolean: return r.GetBoolean(o);
            case global::LightORM.Utils.FieldKind.Int32: return r.GetInt32(o) != 0;
            case global::LightORM.Utils.FieldKind.Int64: return r.GetInt64(o) != 0;
            case global::LightORM.Utils.FieldKind.Int16: return r.GetInt16(o) != 0;
            case global::LightORM.Utils.FieldKind.Byte: return r.GetByte(o) != 0;
            case global::LightORM.Utils.FieldKind.Decimal: return r.GetDecimal(o) != 0;
            case global::LightORM.Utils.FieldKind.String: return global::LightORM.Utils.DataReaderConvert.StringToBoolean(r.GetString(o));
            default: return global::System.Convert.ToBoolean(r.GetValue(o), global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }

    // System.DateTime (init-only)  [LightColumn(CREATE_TIME)]
    private static global::System.DateTime Read_CreateTime(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.CreateTime;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.CreateTime_Kind)
        {
            case global::LightORM.Utils.FieldKind.DateTime: return r.GetDateTime(o);
            case global::LightORM.Utils.FieldKind.DateTimeOffset: return ((global::System.DateTimeOffset)r.GetValue(o)).DateTime;
            case global::LightORM.Utils.FieldKind.String: return global::System.DateTime.Parse(r.GetString(o), global::System.Globalization.CultureInfo.CurrentCulture);
            case global::LightORM.Utils.FieldKind.Int64: return new global::System.DateTime(r.GetInt64(o));
            default: return (global::System.DateTime)global::System.Convert.ChangeType(r.GetValue(o), typeof(global::System.DateTime), global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }

    // System.DateTime?  [LightColumn(MODIFY_TIME)]
    private static global::System.DateTime? Read_ModifyTime(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.ModifyTime;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.ModifyTime_Kind)
        {
            case global::LightORM.Utils.FieldKind.DateTime: return r.GetDateTime(o);
            case global::LightORM.Utils.FieldKind.DateTimeOffset: return ((global::System.DateTimeOffset)r.GetValue(o)).DateTime;
            case global::LightORM.Utils.FieldKind.String: return global::System.DateTime.Parse(r.GetString(o), global::System.Globalization.CultureInfo.CurrentCulture);
            case global::LightORM.Utils.FieldKind.Int64: return new global::System.DateTime(r.GetInt64(o));
            default: return (global::System.DateTime?)global::System.Convert.ChangeType(r.GetValue(o), typeof(global::System.DateTime), global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }
}
