// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

namespace LightORM.GeneratedTableContext;

/// <summary>
/// Compact 档对照：switch 收进运行库的 DataReaderReaders，生成代码只剩一行一列。
/// 优点：生成体积小、编译快；缺点：每列多一次静态方法调用（JIT 可能因方法体过大放弃内联）
///      以及每次进入都要重新 switch。
/// </summary>
internal sealed class ProductDeserializerCompact
    : global::LightORM.Utils.ReaderPlanCache<ProductDeserializerCompact.Plan>
{
    internal sealed class Plan
    {
        public int Id = -1;
        public global::LightORM.Utils.FieldKind Id_Kind;
        public int ProductId = -1;
        public global::LightORM.Utils.FieldKind ProductId_Kind;
        public int CategoryId = -1;
        public global::LightORM.Utils.FieldKind CategoryId_Kind;
        public int ProductCode = -1;
        public global::LightORM.Utils.FieldKind ProductCode_Kind;
        public int ProductName = -1;
        public global::LightORM.Utils.FieldKind ProductName_Kind;
        public int DeleteMark = -1;
        public global::LightORM.Utils.FieldKind DeleteMark_Kind;
        public int CreateTime = -1;
        public global::LightORM.Utils.FieldKind CreateTime_Kind;
        public int ModifyTime = -1;
        public global::LightORM.Utils.FieldKind ModifyTime_Kind;
    }

    private static readonly ProductDeserializerCompact _cache = new();

    public static global::LightORMTest.Models.Product Deserialize(global::System.Data.IDataReader reader)
    {
        var plan = _cache.Get(reader);
        return new global::LightORMTest.Models.Product
        {
            Id = plan.Id < 0 || reader.IsDBNull(plan.Id)
                ? default
                : global::LightORM.Utils.DataReaderReaders.ReadInt32(reader, plan.Id, plan.Id_Kind),

            ProductId = plan.ProductId < 0 || reader.IsDBNull(plan.ProductId)
                ? default
                : global::LightORM.Utils.DataReaderReaders.ReadInt32(reader, plan.ProductId, plan.ProductId_Kind),

            CategoryId = plan.CategoryId < 0 || reader.IsDBNull(plan.CategoryId)
                ? default
                : global::LightORM.Utils.DataReaderReaders.ReadInt32(reader, plan.CategoryId, plan.CategoryId_Kind),

            ProductCode = plan.ProductCode < 0 || reader.IsDBNull(plan.ProductCode)
                ? default!
                : global::LightORM.Utils.DataReaderReaders.ReadString(reader, plan.ProductCode, plan.ProductCode_Kind)!,

            ProductName = plan.ProductName < 0 || reader.IsDBNull(plan.ProductName)
                ? default!
                : global::LightORM.Utils.DataReaderReaders.ReadString(reader, plan.ProductName, plan.ProductName_Kind)!,

            DeleteMark = plan.DeleteMark < 0 || reader.IsDBNull(plan.DeleteMark)
                ? default
                : global::LightORM.Utils.DataReaderReaders.ReadBoolean(reader, plan.DeleteMark, plan.DeleteMark_Kind),

            CreateTime = plan.CreateTime < 0 || reader.IsDBNull(plan.CreateTime)
                ? default
                : global::LightORM.Utils.DataReaderReaders.ReadDateTime(reader, plan.CreateTime, plan.CreateTime_Kind),

            ModifyTime = plan.ModifyTime < 0 || reader.IsDBNull(plan.ModifyTime)
                ? default
                : global::LightORM.Utils.DataReaderReaders.ReadDateTimeN(reader, plan.ModifyTime, plan.ModifyTime_Kind),
        };
    }

    protected override Plan Bind(global::System.Data.IDataReader reader)
    {
        var plan = new Plan();
        int count = reader.FieldCount;
        for (int i = 0; i < count; i++)
        {
            var kind = global::LightORM.Utils.FieldKindResolver.Resolve(reader.GetFieldType(i));
            switch (reader.GetName(i))
            {
                case "Id": case "ID": case "id":
                    plan.Id = i; plan.Id_Kind = kind; break;
                case "PRODUCT_ID": case "product_id":
                    plan.ProductId = i; plan.ProductId_Kind = kind; break;
                case "CATEGORY_ID": case "category_id":
                    plan.CategoryId = i; plan.CategoryId_Kind = kind; break;
                case "PRODUCT_CODE": case "product_code":
                    plan.ProductCode = i; plan.ProductCode_Kind = kind; break;
                case "PRODUCT_NAME": case "product_name":
                    plan.ProductName = i; plan.ProductName_Kind = kind; break;
                case "DELETE_MARK": case "delete_mark":
                    plan.DeleteMark = i; plan.DeleteMark_Kind = kind; break;
                case "CREATE_TIME": case "create_time":
                    plan.CreateTime = i; plan.CreateTime_Kind = kind; break;
                case "MODIFY_TIME": case "modify_time":
                    plan.ModifyTime = i; plan.ModifyTime_Kind = kind; break;
            }
        }

        return plan;
    }
}
