// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

namespace LightORM.GeneratedTableContext;

/// <summary>
/// 覆盖 [LightFlat] 聚合属性：UserFlat.PriInfo (PrivateInfo) 的子列 AGE / IS_LOCK / ADDRESS
/// 平铺进同一个 Plan，读取时内嵌一个 new PrivateInfo { ... } 对象初始化器。
/// </summary>
internal sealed class UserFlatDeserializer
    : global::LightORM.Utils.ReaderPlanCache<UserFlatDeserializer.Plan>
{
    internal sealed class Plan
    {
        // --- 主表列 ---
        public int UserId = -1;
        public global::LightORM.Utils.FieldKind UserId_Kind;
        public int UserName = -1;
        public global::LightORM.Utils.FieldKind UserName_Kind;
        public int Password = -1;
        public global::LightORM.Utils.FieldKind Password_Kind;
        public int Sign = -1;
        public global::LightORM.Utils.FieldKind Sign_Kind;
        public int LastLogin = -1;
        public global::LightORM.Utils.FieldKind LastLogin_Kind;
        public int Version = -1;
        public global::LightORM.Utils.FieldKind Version_Kind;

        // --- Flat 子列（PriInfo）---
        public int PriInfo_Age = -1;
        public global::LightORM.Utils.FieldKind PriInfo_Age_Kind;
        public int PriInfo_IsLock = -1;
        public global::LightORM.Utils.FieldKind PriInfo_IsLock_Kind;
        public int PriInfo_Address = -1;
        public global::LightORM.Utils.FieldKind PriInfo_Address_Kind;
    }

    public static readonly global::System.Func<global::System.Data.IDataReader, global::LightORMTest.Models.UserFlat> Instance = Deserialize;

    private static readonly UserFlatDeserializer _cache = new();

    public static global::LightORMTest.Models.UserFlat Deserialize(global::System.Data.IDataReader reader)
    {
        var plan = _cache.Get(reader);
        return new global::LightORMTest.Models.UserFlat
        {
            UserId = Read_UserId(reader, plan)!,
            UserName = Read_UserName(reader, plan)!,
            Password = Read_Password(reader, plan)!,
            Sign = Read_Sign(reader, plan)!,
            LastLogin = Read_LastLogin(reader, plan),
            Version = Read_Version(reader, plan),
            // 聚合属性：整体作为一个槽位
            PriInfo = Read_PriInfo(reader, plan),
        };
        // 注意：UserRoles 是 [LightNavigate] 导航属性，不参与列映射（与 Expression 方案一致）
    }

    protected override Plan Bind(global::System.Data.IDataReader reader)
    {
        var plan = new Plan();
        int count = reader.FieldCount;
        for (int i = 0; i < count; i++)
        {
            var kind = global::LightORM.Utils.FieldKindResolver.Resolve(reader.GetFieldType(i));
            switch (reader.GetName(i))
            {
                case "USER_ID": case "user_id":
                    plan.UserId = i; plan.UserId_Kind = kind; break;
                case "USER_NAME": case "user_name":
                    plan.UserName = i; plan.UserName_Kind = kind; break;
                case "PASSWORD": case "password":
                    plan.Password = i; plan.Password_Kind = kind; break;
                case "SIGN": case "sign":
                    plan.Sign = i; plan.Sign_Kind = kind; break;
                case "LAST_LOGIN": case "last_login":
                    plan.LastLogin = i; plan.LastLogin_Kind = kind; break;
                case "VER": case "ver":
                    plan.Version = i; plan.Version_Kind = kind; break;

                // Flat 子列
                case "AGE": case "age":
                    plan.PriInfo_Age = i; plan.PriInfo_Age_Kind = kind; break;
                case "IS_LOCK": case "is_lock":
                    plan.PriInfo_IsLock = i; plan.PriInfo_IsLock_Kind = kind; break;
                case "ADDRESS": case "address":
                    plan.PriInfo_Address = i; plan.PriInfo_Address_Kind = kind; break;
            }
        }

        return plan;
    }

    // ---------------------------------------------------------------
    // 聚合属性宿主：PriInfo (PrivateInfo?)
    // 生成期判定：PriInfo 有 setter（非 init-only/readonly）→ 走对象初始化器内嵌
    // 若宿主是只读属性，生成器改为产出下列形状：
    //      var p = new UserFlat { ... };           // 不含 PriInfo
    //      var flat = p.PriInfo ??= new PrivateInfo();
    //      if (plan.PriInfo_Age >= 0 && !reader.IsDBNull(plan.PriInfo_Age))
    //          flat.Age = (int?)...;
    //      return p;
    // ---------------------------------------------------------------
    private static global::LightORMTest.Models.PrivateInfo? Read_PriInfo(global::System.Data.IDataReader r, Plan p)
    {
        // 与 Expression 方案行为一致：无条件 new（即使一个 flat 列都没命中）
        return new global::LightORMTest.Models.PrivateInfo
        {
            Age = Read_PriInfo_Age(r, p),
            IsLock = Read_PriInfo_IsLock(r, p),
            Address = Read_PriInfo_Address(r, p)!,
        };
    }

    // System.Int32?  [LightColumn(AGE)]
    private static int? Read_PriInfo_Age(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.PriInfo_Age;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.PriInfo_Age_Kind)
        {
            case global::LightORM.Utils.FieldKind.Int32: return r.GetInt32(o);
            case global::LightORM.Utils.FieldKind.Int64: return (int)r.GetInt64(o);
            case global::LightORM.Utils.FieldKind.Int16: return r.GetInt16(o);
            case global::LightORM.Utils.FieldKind.Byte: return r.GetByte(o);
            case global::LightORM.Utils.FieldKind.Decimal: return (int)r.GetDecimal(o);
            case global::LightORM.Utils.FieldKind.Double: return (int)r.GetDouble(o);
            case global::LightORM.Utils.FieldKind.Single: return (int)r.GetFloat(o);
            case global::LightORM.Utils.FieldKind.String: return int.Parse(r.GetString(o), global::System.Globalization.CultureInfo.CurrentCulture);
            default: return (int?)global::System.Convert.ChangeType(r.GetValue(o), typeof(int), global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }

    // System.Boolean  [LightColumn(IS_LOCK)]
    private static bool Read_PriInfo_IsLock(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.PriInfo_IsLock;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.PriInfo_IsLock_Kind)
        {
            case global::LightORM.Utils.FieldKind.Boolean: return r.GetBoolean(o);
            case global::LightORM.Utils.FieldKind.Int32: return r.GetInt32(o) != 0;
            case global::LightORM.Utils.FieldKind.Int64: return r.GetInt64(o) != 0;
            case global::LightORM.Utils.FieldKind.Int16: return r.GetInt16(o) != 0;
            case global::LightORM.Utils.FieldKind.Byte: return r.GetByte(o) != 0;
            case global::LightORM.Utils.FieldKind.String: return global::LightORM.Utils.DataReaderConvert.StringToBoolean(r.GetString(o));
            default: return global::System.Convert.ToBoolean(r.GetValue(o), global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }

    // System.String  [LightColumn(ADDRESS)]
    private static string? Read_PriInfo_Address(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.PriInfo_Address;
        if (o < 0 || r.IsDBNull(o)) return default;
        switch (p.PriInfo_Address_Kind)
        {
            case global::LightORM.Utils.FieldKind.String: return r.GetString(o);
            case global::LightORM.Utils.FieldKind.Char: return r.GetChar(o).ToString();
            case global::LightORM.Utils.FieldKind.Bytes: return global::System.Text.Encoding.UTF8.GetString(global::LightORM.Utils.DataReaderConvert.ToBytes(r, o));
            default:
                var v = r.GetValue(o);
                return v is null or global::System.DBNull ? null : global::System.Convert.ToString(v, global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }

    // --- 主表列读取（同 Product，略去重复展开，实际生成时全量输出）---
    private static string? Read_UserId(global::System.Data.IDataReader r, Plan p)
        => p.UserId < 0 || r.IsDBNull(p.UserId) ? default : r.GetString(p.UserId);
    private static string? Read_UserName(global::System.Data.IDataReader r, Plan p)
        => p.UserName < 0 || r.IsDBNull(p.UserName) ? default : r.GetString(p.UserName);
    private static string? Read_Password(global::System.Data.IDataReader r, Plan p)
        => p.Password < 0 || r.IsDBNull(p.Password) ? default : r.GetString(p.Password);
    private static string? Read_Sign(global::System.Data.IDataReader r, Plan p)
        => p.Sign < 0 || r.IsDBNull(p.Sign) ? default : r.GetString(p.Sign);
    private static global::System.DateTime Read_LastLogin(global::System.Data.IDataReader r, Plan p)
        => p.LastLogin < 0 || r.IsDBNull(p.LastLogin) ? default : r.GetDateTime(p.LastLogin);
    private static int Read_Version(global::System.Data.IDataReader r, Plan p)
        => p.Version < 0 || r.IsDBNull(p.Version) ? default : r.GetInt32(p.Version);
}
