// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

namespace LightORM.GeneratedTableContext;

/// <summary>
/// 覆盖 [LightJsonMap] 列。
/// 与 Expression 方案的差别：Expression 版是
///     Expression.Call(StringDeserializer, GetString(o), Expression.Constant(typeof(JsonData)))
/// 即运行时传 Type 走反射重载 —— AOT 下不安全。
/// 生成器版直接写死泛型实参 <see cref="global::LightORMTest.Models.JsonData"/>，
/// 可接入 System.Text.Json 的 JsonTypeInfo&lt;T&gt; 源生成路径。
/// </summary>
internal sealed class JsonTestModelDeserializer
    : global::LightORM.Utils.ReaderPlanCache<JsonTestModelDeserializer.Plan>
{
    internal sealed class Plan
    {
        public int Id = -1;
        public global::LightORM.Utils.FieldKind Id_Kind;
        public int Json = -1;
        public global::LightORM.Utils.FieldKind Json_Kind;
        public int JsonList = -1;
        public global::LightORM.Utils.FieldKind JsonList_Kind;
        public int JsonArray = -1;
        public global::LightORM.Utils.FieldKind JsonArray_Kind;
        public int JsonObject = -1;
        public global::LightORM.Utils.FieldKind JsonObject_Kind;
    }

    public static readonly global::System.Func<global::System.Data.IDataReader, global::LightORMTest.Models.JsonTestModel> Instance = Deserialize;

    private static readonly JsonTestModelDeserializer _cache = new();

    public static global::LightORMTest.Models.JsonTestModel Deserialize(global::System.Data.IDataReader reader)
    {
        var plan = _cache.Get(reader);
        return new global::LightORMTest.Models.JsonTestModel
        {
            Id = Read_Id(reader, plan),
            Json = Read_Json(reader, plan),
            JsonList = Read_JsonList(reader, plan),
            JsonArray = Read_JsonArray(reader, plan),
            JsonObject = Read_JsonObject(reader, plan)!,
        };
    }

    protected override Plan Bind(global::System.Data.IDataReader reader)
    {
        var plan = new Plan();
        int count = reader.FieldCount;
        for (int i = 0; i < count; i++)
        {
            var kind = global::LightORM.Utils.FieldKindResolver.Resolve(reader.GetFieldType(i));
            switch (reader.GetName(i))
            {
                case "ID": case "id":
                    plan.Id = i; plan.Id_Kind = kind; break;
                case "JSON_DATA": case "json_data":
                    plan.Json = i; plan.Json_Kind = kind; break;
                case "JSON_DATA_LIST": case "json_data_list":
                    plan.JsonList = i; plan.JsonList_Kind = kind; break;
                case "JSON_DATA_ARRAY": case "json_data_array":
                    plan.JsonArray = i; plan.JsonArray_Kind = kind; break;
                case "JSON_DATA_ELEMENT": case "json_data_element":
                    plan.JsonObject = i; plan.JsonObject_Kind = kind; break;
            }
        }

        return plan;
    }

    private static int Read_Id(global::System.Data.IDataReader r, Plan p)
        => p.Id < 0 || r.IsDBNull(p.Id) ? default : r.GetInt32(p.Id);

    // ---------------------------------------------------------------
    // JSON 列：统一先取文本（string 或 byte[]），再交给 JsonHandler
    // AOT 关键点：Deserialize<T>(string) 走的是 JsonTypeInfo<T> 重载，
    // 由调用方（这里是生成代码）在编译期提供 T，配合 JsonSerializerContext
    // 即可完全裁剪安全；不再需要 Expression.Constant(typeof(T)) 那种反射路径。
    // ---------------------------------------------------------------

    // JsonData?  [LightJsonMap]
    private static global::LightORMTest.Models.JsonData? Read_Json(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.Json;
        if (o < 0 || r.IsDBNull(o)) return default;
        var text = ReadJsonText(r, o, p.Json_Kind);
        return string.IsNullOrEmpty(text)
            ? default
            : global::LightORM.Utils.JsonHandler.Deserialize<global::LightORMTest.Models.JsonData>(text!);
    }

    // List<JsonData>?  [LightJsonMap]
    private static global::System.Collections.Generic.List<global::LightORMTest.Models.JsonData>? Read_JsonList(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.JsonList;
        if (o < 0 || r.IsDBNull(o)) return default;
        var text = ReadJsonText(r, o, p.JsonList_Kind);
        return string.IsNullOrEmpty(text)
            ? default
            : global::LightORM.Utils.JsonHandler.Deserialize<global::System.Collections.Generic.List<global::LightORMTest.Models.JsonData>>(text!);
    }

    // JsonData[]?  [LightJsonMap]
    private static global::LightORMTest.Models.JsonData[]? Read_JsonArray(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.JsonArray;
        if (o < 0 || r.IsDBNull(o)) return default;
        var text = ReadJsonText(r, o, p.JsonArray_Kind);
        return string.IsNullOrEmpty(text)
            ? default
            : global::LightORM.Utils.JsonHandler.Deserialize<global::LightORMTest.Models.JsonData[]>(text!);
    }

    // JsonObject  [LightJsonMap]
    private static global::System.Text.Json.Nodes.JsonObject? Read_JsonObject(global::System.Data.IDataReader r, Plan p)
    {
        int o = p.JsonObject;
        if (o < 0 || r.IsDBNull(o)) return default;
        var text = ReadJsonText(r, o, p.JsonObject_Kind);
        return string.IsNullOrEmpty(text)
            ? default
            : global::LightORM.Utils.JsonHandler.Deserialize<global::System.Text.Json.Nodes.JsonObject>(text!);
    }

    private static string? ReadJsonText(global::System.Data.IDataReader r, int o, global::LightORM.Utils.FieldKind kind)
    {
        switch (kind)
        {
            case global::LightORM.Utils.FieldKind.String:
                return r.GetString(o);
            case global::LightORM.Utils.FieldKind.Bytes:
                return global::System.Text.Encoding.UTF8.GetString(global::LightORM.Utils.DataReaderConvert.ToBytes(r, o));
            default:
                var v = r.GetValue(o);
                return v is null or global::System.DBNull ? null : global::System.Convert.ToString(v, global::System.Globalization.CultureInfo.CurrentCulture);
        }
    }
}
