using Generators.Shared;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;

namespace LightOrmExtensionGenerator
{
    /// <summary>
    /// 
    /// </summary>
    /// <typeparam name="T1"></typeparam>
    /// <typeparam name="T2"></typeparam>
    /// <param name="t1"></param>
    /// <param name="t2"></param>
    public class TypeSet<
#if NET8_0_OR_GREATER
    [System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All)]
#endif
T1,
#if NET8_0_OR_GREATER
    [System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All)]
#endif
T2
>(T1 t1, T2 t2)
    {
        /// <summary>
        /// 
        /// </summary>
        public T1 Tb1 { get; } = t1;
        public T2 Tb2 { get; } = t2;

    }
    public abstract class GeneratorBase : IIncrementalGenerator
    {
        public const string TargetAttribute = "LightORM.DbEntity.Attributes.SelectExtensionAttribute";
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var source = context.SyntaxProvider.ForAttributeWithMetadataName(
                TargetAttribute
                , static (node, _) => true
                , (ctx, _) => ctx);

            context.RegisterSourceOutput(source, RegisterOutput);
            void RegisterOutput(SourceProductionContext context, GeneratorAttributeSyntaxContext source)
            {
                var target = (IAssemblySymbol)source.TargetSymbol;
                var attrs = target.GetAttributes(TargetAttribute);
                StringBuilder codes = new($"""
                    // <auto-generated/>
                    #pragma warning disable
                    #nullable enable
                    using System.Threading; 
                    namespace {Namespace()};
                    """);
                foreach (var item in attrs)
                {
                    if (!Enable(item))
                    {
                        continue;
                    }
                    var result = Handler(item);
                    codes.AppendLine(result);
                }
                context.AddSource(FileName(), SourceText.From(codes.ToString(), Encoding.UTF8));
            }
        }

        public abstract string Handler(AttributeData data);
        public virtual bool Enable(AttributeData data)
        {
            var count = (int)data.GetNamedValue("ArgumentCount")!;
            return count > 2 && count < 17;
        }
        public abstract string FileName();
        public virtual string Namespace() => "LightORM";
        protected static string GetTypesString(int count)
        {
            var args = Enumerable.Range(1, count).Select(i => $"T{i}");
            var argsStr = string.Join(", ", args);
            return argsStr;
        }

        protected static string GetTypesString(int count, Func<int, string> func, string separator)
        {
            var args = Enumerable.Range(1, count).Select(func);
            var argsStr = string.Join(separator, args);
            return argsStr;
        }
    }
}
