using Generators.Shared;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace LightOrmExtensionGenerator
{
    public abstract class GeneratorBase : IIncrementalGenerator
    {
        public const string TargetAttribute = "LightORM.DbEntity.Attributes.SelectExtensionAttribute";
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var source = context.SyntaxProvider.ForAttributeWithMetadataName(
                TargetAttribute
                , static (node, _) => true
                , (ctx, _) => ctx);

            context.RegisterSourceOutput(source, RegisterOutput);
            void RegisterOutput(SourceProductionContext context, GeneratorAttributeSyntaxContext source)
            {
                var target = (IAssemblySymbol)source.TargetSymbol;
                var attrs = target.GetAttributes(TargetAttribute);
                StringBuilder codes = new($"""
                    // <auto-generated/>
                    #pragma warning disable
                    #nullable enable
                    using System.Threading; 
                    namespace {Namespace()};
                    """);
                foreach (var item in attrs)
                {
                    var result = Handler(item);
                    codes.AppendLine(result);
                }
                context.AddSource(FileName(), SourceText.From(codes.ToString(), Encoding.UTF8));
            }
        }

        public abstract string Handler(AttributeData data);
        public abstract string FileName();
        public virtual string Namespace() => "LightORM";
        protected static string GetTypesString(int count)
        {
            var args = Enumerable.Range(1, count).Select(i => $"T{i}");
            var argsStr = string.Join(", ", args);
            return argsStr;
        }
    }
}
