<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../versions.props"/>
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>MarvelTiter</Authors>
		<Description>LightORM SqlServer扩展</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageReadmeFile>Nuget.md</PackageReadmeFile>
		<Version>$(SqlServerVersion)</Version>
	</PropertyGroup>
	<Import Project="..\..\SupportedFrameworks.props" />
	<ItemGroup>
		<None Include="..\..\Nuget.md">
			<PackagePath>\</PackagePath>
			<Pack>True</Pack>
		</None>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'RELEASE'">
		<PackageReference Include="MT.LightORM" Version="$(SqlServerDepVersion)" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' == 'DEBUG'">
		<ProjectReference Include="..\..\LightORM\LightORM.csproj" />
	</ItemGroup>

</Project>
