using Microsoft.CodeAnalysis;
using System.Linq;

namespace Generators.Shared.Builder;

internal class NamespaceBuilder : TypeBuilder<NamespaceBuilder>
{
    public NamespaceBuilder() { }
    public override NodeType Type => NodeType.NameSpace;
    public string? Namespace { get; set; }
    public override string ToString()
    {
        return
$$"""
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace {{Namespace}}
{
{{string.Join("\t", Members)}}
}
""";
    }
}
